"""`aspose-email-mcp`'s own standalone, runnable MCP server.

Auto-generated by Codegen's `generate_server_module_source` from the tracked IR — regenerate via
`run_lifecycle.py --product email --action rebuild` instead of patching this file directly
(rubric gate 8: hand-patched generated output is a hard-gate failure, same discipline this
package's own `tools.py` header states).

This is the real runnable entry point the public `aspose-email-mcp` package ships. Before
this file existed, the only actual MCP server for this product lived inside the private builder
repo's own staging area (its `generated/email/server.py`), which imports the builder's own
internal auth client, tool-spec builder, IR document schema, lessons store, and semantic-db
modules directly, and loaded a live `ir/email/*.json` snapshot at import time just to
recompute each tool's annotations and structured-output flag. None of that exists once this
package is the only thing actually published (Decision 6: every "published" release so far has
only ever been a GitLab tag of the *tools library*, `tools.py` — never a runnable server) — so
this file is a deliberate, self-contained rendering with **zero import dependency on the private
builder package**, mirroring every other file in this package's own zero-import-dependency-on-
the-builder discipline (see this package's own `_auth.py`/`_path_resolution.py` docstrings).
Every tool's annotations and
`structured_output` flag are baked into this file as literal values at the time it was
generated — never recomputed from a live IR file at server startup, since no IR file ships with
this package.

Bundles Storage's core-4 tools (FR15b) exactly like the existing staging-area servers do, so a
user connected to only this server can upload a file, operate on it, and download the result
with no second server connection.
"""

from __future__ import annotations

from typing import Any

from aspose_storage_core_mcp import (
    DeleteFileResponse,
    storage_delete_file,
    storage_download_file,
    storage_list_files,
    storage_upload_file,
)
from aspose_email_mcp import (
    AiNameCompleteResponse,
    AiNameExpandResponse,
    AiNameFormatResponse,
    AiNameGenderizeResponse,
    AiNameMatchResponse,
    AiNameParseEmailAddressResponse,
    AiNameParseResponse,
    CalendarGetAsAlternateResponse,
    CalendarGetListResponse,
    CalendarGetResponse,
    ClientAccountGetMultiResponse,
    ClientAccountGetResponse,
    ClientFolderGetListResponse,
    ClientMessageFetchResponse,
    ClientMessageListResponse,
    ClientThreadGetListResponse,
    ClientThreadGetMessagesResponse,
    ContactGetListResponse,
    ContactGetResponse,
    DisposableEmailIsDisposableResponse,
    EmailConfigDiscoverResponse,
    EmailFromFileResponse,
    EmailGetListResponse,
    GetDiscUsageResponse,
    GetFileVersionsResponse,
    GetFilesListResponse,
    MapiCalendarGetResponse,
    MapiContactGetResponse,
    MapiMessageGetResponse,
    StorageExistsResponse,
    email_convert_file,
    email_create_client_message,
    email_delete_client_folder,
    email_delete_client_message,
    email_delete_client_thread,
    email_delete_storage_file,
    email_delete_storage_folder,
    email_extract_properties,
    email_get_ai_name_complete,
    email_get_ai_name_expand,
    email_get_ai_name_format,
    email_get_ai_name_genderize,
    email_get_ai_name_match,
    email_get_ai_name_parse,
    email_get_ai_name_parse_email_address,
    email_get_as_file,
    email_get_calendar,
    email_get_calendar_as_alternate,
    email_get_calendar_as_file,
    email_get_calendar_list,
    email_get_client_account,
    email_get_client_account_multi,
    email_get_client_folder_list,
    email_get_client_message,
    email_get_client_message_file,
    email_get_client_message_list,
    email_get_client_thread_list,
    email_get_client_thread_messages,
    email_get_config_discover,
    email_get_contact,
    email_get_contact_as_file,
    email_get_contact_list,
    email_get_disposable_is_disposable,
    email_get_list,
    email_get_mapi_calendar,
    email_get_mapi_contact,
    email_get_mapi_message,
    email_get_storage_disc,
    email_get_storage_exist,
    email_get_storage_file,
    email_get_storage_folder,
    email_get_storage_version,
    email_update_storage_file_copy,
    email_update_storage_file_move,
    email_update_storage_folder,
    email_update_storage_folder_copy,
    email_update_storage_folder_move,
)
from aspose_email_mcp._auth import AsposeAuthClient
from mcp.server.mcpserver import MCPServer
from mcp_types import ToolAnnotations


server = MCPServer(
    "aspose-email",
    version="0.1.0",
    instructions="Real Codegen-generated MCP tools for Email's curated operation set, plus Storage's bundled core subset (upload/download/list/delete).",
)


_auth: AsposeAuthClient | None = None


def _get_auth() -> AsposeAuthClient:
    global _auth
    if _auth is None:
        _auth = AsposeAuthClient()
    return _auth


# --- Bundled Storage core subset (FR15b) ----------------------------------------------------


def storage_upload_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, content_base64: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    # Sprint 11 real bug fix: `storage_upload_file`/`storage_delete_file` gained a `base_url`
    # parameter (Slides' v3.0 finding) inserted *before* `dry_run` in their real signatures -- a
    # positional call here would have silently passed `dry_run`'s value into `base_url` instead
    # (a real, confirmed bug, never actually exercised until now). Every storage-core call below is
    # keyword-only from this point on, immune to any future parameter reordering.
    return storage_upload_file(_get_auth(), "email", filename, version_id=version_id, storage_name=storage_name, content_base64=content_base64, dry_run=dry_run)


def storage_download_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return storage_download_file(_get_auth(), "email", filename, version_id=version_id, storage_name=storage_name, output_filename=output_filename, return_base64=return_base64)


def storage_list_files_tool(folder_name: str | None = None, storage_name: str | None = None) -> dict[str, Any]:
    return storage_list_files(_get_auth(), "email", folder_name=folder_name, storage_name=storage_name)


def storage_delete_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> DeleteFileResponse:
    return storage_delete_file(_get_auth(), "email", filename, version_id=version_id, storage_name=storage_name, dry_run=dry_run)


_STORAGE_ANNOTATIONS = {
    "storage_upload_file": {"title": "Upload a file to Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False},
    "storage_download_file": {"title": "Download a file from Aspose Cloud Storage", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_list_files": {"title": "List files in an Aspose Cloud Storage folder", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_delete_file": {"title": "Delete a file from Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True},
}


_STORAGE_WRAPPERS = {
    "storage_upload_file": storage_upload_file_tool,
    "storage_download_file": storage_download_file_tool,
    "storage_list_files": storage_list_files_tool,
    "storage_delete_file": storage_delete_file_tool,
}

_STORAGE_REAL_FUNCS = {
    "storage_upload_file": storage_upload_file,
    "storage_download_file": storage_download_file,
    "storage_list_files": storage_list_files,
    "storage_delete_file": storage_delete_file,
}


# --- Email's own curated tools ------------------------------------------------------------


def email_get_calendar_tool(file_name: str, folder: str | None = None, storage: str | None = None) -> CalendarGetResponse:
    return email_get_calendar(_get_auth(), file_name=file_name, folder=folder, storage=storage)


def email_get_calendar_list_tool(folder: str, items_per_page: str | None = None, page_number: str | None = None, storage: str | None = None) -> CalendarGetListResponse:
    return email_get_calendar_list(_get_auth(), folder=folder, items_per_page=items_per_page, page_number=page_number, storage=storage)


def email_get_calendar_as_alternate_tool(file_name: str, calendar_action: str, sequence_id: str | None = None, folder: str | None = None, storage: str | None = None) -> CalendarGetAsAlternateResponse:
    return email_get_calendar_as_alternate(_get_auth(), file_name=file_name, calendar_action=calendar_action, sequence_id=sequence_id, folder=folder, storage=storage)


def email_get_calendar_as_file_tool(file_name: str, format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    return email_get_calendar_as_file(_get_auth(), file_name=file_name, format=format, storage=storage, folder=folder)


def email_get_contact_tool(format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> ContactGetResponse:
    return email_get_contact(_get_auth(), format=format, file_name=file_name, folder=folder, storage=storage)


def email_get_contact_list_tool(format: str, folder: str | None = None, storage: str | None = None, items_per_page: str | None = None, page_number: str | None = None) -> ContactGetListResponse:
    return email_get_contact_list(_get_auth(), format=format, folder=folder, storage=storage, items_per_page=items_per_page, page_number=page_number)


def email_get_contact_as_file_tool(file_name: str, to_format: str, from_format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    return email_get_contact_as_file(_get_auth(), file_name=file_name, to_format=to_format, from_format=from_format, storage=storage, folder=folder)


def email_get_list_tool(format: str, folder: str | None = None, storage: str | None = None, items_per_page: str | None = None, page_number: str | None = None) -> EmailGetListResponse:
    return email_get_list(_get_auth(), format=format, folder=folder, storage=storage, items_per_page=items_per_page, page_number=page_number)


def email_get_as_file_tool(file_name: str, format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    return email_get_as_file(_get_auth(), file_name=file_name, format=format, storage=storage, folder=folder)


def email_extract_properties_tool(content_filename: str, source_format: str, content_base64: str | None = None, dry_run: bool = False) -> EmailFromFileResponse:
    return email_extract_properties(_get_auth(), content_filename=content_filename, source_format=source_format, content_base64=content_base64, dry_run=dry_run)


def email_convert_file_tool(content_filename: str, source_format: str, target_format: str, content_base64: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return email_convert_file(_get_auth(), content_filename=content_filename, source_format=source_format, target_format=target_format, content_base64=content_base64, output_filename=output_filename, return_base64=return_base64)


def email_get_mapi_calendar_tool(file_name: str, folder: str | None = None, storage: str | None = None) -> MapiCalendarGetResponse:
    return email_get_mapi_calendar(_get_auth(), file_name=file_name, folder=folder, storage=storage)


def email_get_mapi_contact_tool(format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> MapiContactGetResponse:
    return email_get_mapi_contact(_get_auth(), format=format, file_name=file_name, folder=folder, storage=storage)


def email_get_mapi_message_tool(format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> MapiMessageGetResponse:
    return email_get_mapi_message(_get_auth(), format=format, file_name=file_name, folder=folder, storage=storage)


def email_get_disposable_is_disposable_tool(address: str) -> DisposableEmailIsDisposableResponse:
    return email_get_disposable_is_disposable(_get_auth(), address=address)


def email_get_config_discover_tool(address: str, fast_processing: bool | None = None) -> EmailConfigDiscoverResponse:
    return email_get_config_discover(_get_auth(), address=address, fast_processing=fast_processing)


def email_get_client_account_tool(file_name: str, folder: str | None = None, storage: str | None = None) -> ClientAccountGetResponse:
    return email_get_client_account(_get_auth(), file_name=file_name, folder=folder, storage=storage)


def email_get_client_account_multi_tool(file_name: str, folder: str | None = None, storage: str | None = None) -> ClientAccountGetMultiResponse:
    return email_get_client_account_multi(_get_auth(), file_name=file_name, folder=folder, storage=storage)


def email_delete_client_folder_tool(request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    return email_delete_client_folder(_get_auth(), request=request, dry_run=dry_run)


def email_get_client_folder_list_tool(account: str, storage: str | None = None, account_storage_folder: str | None = None, parent_folder: str | None = None) -> ClientFolderGetListResponse:
    return email_get_client_folder_list(_get_auth(), account=account, storage=storage, account_storage_folder=account_storage_folder, parent_folder=parent_folder)


def email_create_client_message_tool(request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    return email_create_client_message(_get_auth(), request=request, dry_run=dry_run)


def email_get_client_message_tool(message_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, type: str | None = None, format: str | None = None) -> ClientMessageFetchResponse:
    return email_get_client_message(_get_auth(), message_id=message_id, account=account, folder=folder, storage=storage, account_storage_folder=account_storage_folder, type=type, format=format)


def email_delete_client_message_tool(request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    return email_delete_client_message(_get_auth(), request=request, dry_run=dry_run)


def email_get_client_message_file_tool(message_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, format: str | None = None) -> dict[str, Any]:
    return email_get_client_message_file(_get_auth(), message_id=message_id, account=account, folder=folder, storage=storage, account_storage_folder=account_storage_folder, format=format)


def email_get_client_message_list_tool(folder: str, account: str, query_string: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, recursive: bool | None = None, type: str | None = None, format: str | None = None) -> ClientMessageListResponse:
    return email_get_client_message_list(_get_auth(), folder=folder, account=account, query_string=query_string, storage=storage, account_storage_folder=account_storage_folder, recursive=recursive, type=type, format=format)


def email_get_client_thread_list_tool(folder: str, account: str, storage: str | None = None, account_storage_folder: str | None = None, update_folder_cache: bool | None = None, messages_cache_limit: str | None = None) -> ClientThreadGetListResponse:
    return email_get_client_thread_list(_get_auth(), folder=folder, account=account, storage=storage, account_storage_folder=account_storage_folder, update_folder_cache=update_folder_cache, messages_cache_limit=messages_cache_limit)


def email_get_client_thread_messages_tool(thread_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None) -> ClientThreadGetMessagesResponse:
    return email_get_client_thread_messages(_get_auth(), thread_id=thread_id, account=account, folder=folder, storage=storage, account_storage_folder=account_storage_folder)


def email_delete_client_thread_tool(request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    return email_delete_client_thread(_get_auth(), request=request, dry_run=dry_run)


def email_get_ai_name_parse_tool(name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameParseResponse:
    return email_get_ai_name_parse(_get_auth(), name=name, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_ai_name_genderize_tool(name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameGenderizeResponse:
    return email_get_ai_name_genderize(_get_auth(), name=name, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_ai_name_complete_tool(name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameCompleteResponse:
    return email_get_ai_name_complete(_get_auth(), name=name, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_ai_name_format_tool(name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, format: str | None = None, style: str | None = None) -> AiNameFormatResponse:
    return email_get_ai_name_format(_get_auth(), name=name, language=language, location=location, encoding=encoding, script=script, format=format, style=style)


def email_get_ai_name_expand_tool(name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameExpandResponse:
    return email_get_ai_name_expand(_get_auth(), name=name, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_ai_name_match_tool(name: str, other_name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameMatchResponse:
    return email_get_ai_name_match(_get_auth(), name=name, other_name=other_name, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_ai_name_parse_email_address_tool(email_address: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameParseEmailAddressResponse:
    return email_get_ai_name_parse_email_address(_get_auth(), email_address=email_address, language=language, location=location, encoding=encoding, script=script, style=style)


def email_get_storage_file_tool(path: str, storage_name: str | None = None, version_id: str | None = None) -> dict[str, Any]:
    return email_get_storage_file(_get_auth(), path=path, storage_name=storage_name, version_id=version_id)


def email_delete_storage_file_tool(path: str, storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_delete_storage_file(_get_auth(), path=path, storage_name=storage_name, version_id=version_id, dry_run=dry_run)


def email_update_storage_file_copy_tool(src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_update_storage_file_copy(_get_auth(), src_path=src_path, dest_path=dest_path, src_storage_name=src_storage_name, dest_storage_name=dest_storage_name, version_id=version_id, dry_run=dry_run)


def email_update_storage_file_move_tool(src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_update_storage_file_move(_get_auth(), src_path=src_path, dest_path=dest_path, src_storage_name=src_storage_name, dest_storage_name=dest_storage_name, version_id=version_id, dry_run=dry_run)


def email_get_storage_folder_tool(path: str, storage_name: str | None = None) -> GetFilesListResponse:
    return email_get_storage_folder(_get_auth(), path=path, storage_name=storage_name)


def email_update_storage_folder_tool(path: str, storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_update_storage_folder(_get_auth(), path=path, storage_name=storage_name, dry_run=dry_run)


def email_delete_storage_folder_tool(path: str, storage_name: str | None = None, recursive: bool | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_delete_storage_folder(_get_auth(), path=path, storage_name=storage_name, recursive=recursive, dry_run=dry_run)


def email_update_storage_folder_copy_tool(src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_update_storage_folder_copy(_get_auth(), src_path=src_path, dest_path=dest_path, src_storage_name=src_storage_name, dest_storage_name=dest_storage_name, dry_run=dry_run)


def email_update_storage_folder_move_tool(src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    return email_update_storage_folder_move(_get_auth(), src_path=src_path, dest_path=dest_path, src_storage_name=src_storage_name, dest_storage_name=dest_storage_name, dry_run=dry_run)


def email_get_storage_exist_tool(storage_name: str) -> StorageExistsResponse:
    return email_get_storage_exist(_get_auth(), storage_name=storage_name)


def email_get_storage_disc_tool(storage_name: str | None = None) -> GetDiscUsageResponse:
    return email_get_storage_disc(_get_auth(), storage_name=storage_name)


def email_get_storage_version_tool(path: str, storage_name: str | None = None) -> GetFileVersionsResponse:
    return email_get_storage_version(_get_auth(), path=path, storage_name=storage_name)


_PRODUCT_ANNOTATIONS = {
    "email_get_calendar": {"title": 'Get calendar file from storage.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_calendar_list": {"title": 'Get iCalendar list from storage folder.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_calendar_as_alternate": {"title": 'Get iCalendar from storage as AlternateView\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_calendar_as_file": {"title": 'Converts calendar document from storage to specified format and returns as file.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_contact": {"title": 'Get contact document from storage.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_contact_list": {"title": 'Get contact list from storage folder.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_contact_as_file": {"title": 'Converts contact document from storage to specified format and returns as file\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_list": {"title": 'Get email list from storage folder.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_as_file": {"title": 'Converts email document from storage to specified format and returns as file\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_extract_properties": {"title": 'Extract structured metadata from a local email file', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_convert_file": {"title": 'Convert a local email file to another format', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_mapi_calendar": {"title": 'Get MAPI calendar document.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_mapi_contact": {"title": 'Get MAPI contact document.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_mapi_message": {"title": 'Get MAPI message document.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_disposable_is_disposable": {"title": 'Check email address is disposable\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_config_discover": {"title": 'Discover email accounts by email address.\nDoes not validate discovered accounts.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_client_account": {"title": 'Get email client account from storage.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_client_account_multi": {"title": 'Get email client multi account file (*.multi.account).\nWill respond error if file extension is not ".multi.account".\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_delete_client_folder": {"title": 'Delete a folder in email account\n            ', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "email_get_client_folder_list": {"title": 'Get folders list in email account\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_create_client_message": {"title": 'Send an email specified by model in request.\n            ', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_get_client_message": {"title": 'Fetch message from email account\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_delete_client_message": {"title": 'Delete message.\n            ', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "email_get_client_message_file": {"title": 'Fetch message as file from email account\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_client_message_list": {"title": 'Get messages from folder, filtered by query\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_client_thread_list": {"title": 'Get message threads from folder.\nAll messages are partly fetched (without email body and some other fields).\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_client_thread_messages": {"title": 'Get messages from thread by id. All messages are fully fetched.\nFor accounts with CacheFile only cached messages will be returned.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_delete_client_thread": {"title": 'Delete thread by id. All messages from thread will also be deleted.\n            ', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "email_get_ai_name_parse": {"title": 'Parse name to components.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_genderize": {"title": "Detect person's gender from name string.\n            ", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_complete": {"title": 'The call proposes k most probable names for given starting characters.\n            ', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_format": {"title": "Formats a person's name in correct case and name order using options for formatting\ninstructions.\n            ", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_expand": {"title": "Expands a person's name into a list of possible alternatives using options for expanding\ninstructions.\n            ", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_match": {"title": "Compare people's names. Uses options for comparing instructions.\n            ", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_ai_name_parse_email_address": {"title": "Parse person's name out of an email address.\n            ", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_storage_file": {"title": 'Download file', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_delete_storage_file": {"title": 'Delete file', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "email_update_storage_file_copy": {"title": 'Copy file', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_update_storage_file_move": {"title": 'Move file', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_get_storage_folder": {"title": 'Get all files and folders within a folder', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_update_storage_folder": {"title": 'Create the folder', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_delete_storage_folder": {"title": 'Delete folder', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "email_update_storage_folder_copy": {"title": 'Copy folder', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_update_storage_folder_move": {"title": 'Move folder', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": False},
    "email_get_storage_exist": {"title": 'Check if storage exists', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_storage_disc": {"title": 'Get disc usage', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "email_get_storage_version": {"title": 'Get file versions', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
}


_PRODUCT_WRAPPERS = {
    "email_get_calendar": email_get_calendar_tool,
    "email_get_calendar_list": email_get_calendar_list_tool,
    "email_get_calendar_as_alternate": email_get_calendar_as_alternate_tool,
    "email_get_calendar_as_file": email_get_calendar_as_file_tool,
    "email_get_contact": email_get_contact_tool,
    "email_get_contact_list": email_get_contact_list_tool,
    "email_get_contact_as_file": email_get_contact_as_file_tool,
    "email_get_list": email_get_list_tool,
    "email_get_as_file": email_get_as_file_tool,
    "email_extract_properties": email_extract_properties_tool,
    "email_convert_file": email_convert_file_tool,
    "email_get_mapi_calendar": email_get_mapi_calendar_tool,
    "email_get_mapi_contact": email_get_mapi_contact_tool,
    "email_get_mapi_message": email_get_mapi_message_tool,
    "email_get_disposable_is_disposable": email_get_disposable_is_disposable_tool,
    "email_get_config_discover": email_get_config_discover_tool,
    "email_get_client_account": email_get_client_account_tool,
    "email_get_client_account_multi": email_get_client_account_multi_tool,
    "email_delete_client_folder": email_delete_client_folder_tool,
    "email_get_client_folder_list": email_get_client_folder_list_tool,
    "email_create_client_message": email_create_client_message_tool,
    "email_get_client_message": email_get_client_message_tool,
    "email_delete_client_message": email_delete_client_message_tool,
    "email_get_client_message_file": email_get_client_message_file_tool,
    "email_get_client_message_list": email_get_client_message_list_tool,
    "email_get_client_thread_list": email_get_client_thread_list_tool,
    "email_get_client_thread_messages": email_get_client_thread_messages_tool,
    "email_delete_client_thread": email_delete_client_thread_tool,
    "email_get_ai_name_parse": email_get_ai_name_parse_tool,
    "email_get_ai_name_genderize": email_get_ai_name_genderize_tool,
    "email_get_ai_name_complete": email_get_ai_name_complete_tool,
    "email_get_ai_name_format": email_get_ai_name_format_tool,
    "email_get_ai_name_expand": email_get_ai_name_expand_tool,
    "email_get_ai_name_match": email_get_ai_name_match_tool,
    "email_get_ai_name_parse_email_address": email_get_ai_name_parse_email_address_tool,
    "email_get_storage_file": email_get_storage_file_tool,
    "email_delete_storage_file": email_delete_storage_file_tool,
    "email_update_storage_file_copy": email_update_storage_file_copy_tool,
    "email_update_storage_file_move": email_update_storage_file_move_tool,
    "email_get_storage_folder": email_get_storage_folder_tool,
    "email_update_storage_folder": email_update_storage_folder_tool,
    "email_delete_storage_folder": email_delete_storage_folder_tool,
    "email_update_storage_folder_copy": email_update_storage_folder_copy_tool,
    "email_update_storage_folder_move": email_update_storage_folder_move_tool,
    "email_get_storage_exist": email_get_storage_exist_tool,
    "email_get_storage_disc": email_get_storage_disc_tool,
    "email_get_storage_version": email_get_storage_version_tool,
}


_PRODUCT_REAL_FUNCS = {
    "email_get_calendar": email_get_calendar,
    "email_get_calendar_list": email_get_calendar_list,
    "email_get_calendar_as_alternate": email_get_calendar_as_alternate,
    "email_get_calendar_as_file": email_get_calendar_as_file,
    "email_get_contact": email_get_contact,
    "email_get_contact_list": email_get_contact_list,
    "email_get_contact_as_file": email_get_contact_as_file,
    "email_get_list": email_get_list,
    "email_get_as_file": email_get_as_file,
    "email_extract_properties": email_extract_properties,
    "email_convert_file": email_convert_file,
    "email_get_mapi_calendar": email_get_mapi_calendar,
    "email_get_mapi_contact": email_get_mapi_contact,
    "email_get_mapi_message": email_get_mapi_message,
    "email_get_disposable_is_disposable": email_get_disposable_is_disposable,
    "email_get_config_discover": email_get_config_discover,
    "email_get_client_account": email_get_client_account,
    "email_get_client_account_multi": email_get_client_account_multi,
    "email_delete_client_folder": email_delete_client_folder,
    "email_get_client_folder_list": email_get_client_folder_list,
    "email_create_client_message": email_create_client_message,
    "email_get_client_message": email_get_client_message,
    "email_delete_client_message": email_delete_client_message,
    "email_get_client_message_file": email_get_client_message_file,
    "email_get_client_message_list": email_get_client_message_list,
    "email_get_client_thread_list": email_get_client_thread_list,
    "email_get_client_thread_messages": email_get_client_thread_messages,
    "email_delete_client_thread": email_delete_client_thread,
    "email_get_ai_name_parse": email_get_ai_name_parse,
    "email_get_ai_name_genderize": email_get_ai_name_genderize,
    "email_get_ai_name_complete": email_get_ai_name_complete,
    "email_get_ai_name_format": email_get_ai_name_format,
    "email_get_ai_name_expand": email_get_ai_name_expand,
    "email_get_ai_name_match": email_get_ai_name_match,
    "email_get_ai_name_parse_email_address": email_get_ai_name_parse_email_address,
    "email_get_storage_file": email_get_storage_file,
    "email_delete_storage_file": email_delete_storage_file,
    "email_update_storage_file_copy": email_update_storage_file_copy,
    "email_update_storage_file_move": email_update_storage_file_move,
    "email_get_storage_folder": email_get_storage_folder,
    "email_update_storage_folder": email_update_storage_folder,
    "email_delete_storage_folder": email_delete_storage_folder,
    "email_update_storage_folder_copy": email_update_storage_folder_copy,
    "email_update_storage_folder_move": email_update_storage_folder_move,
    "email_get_storage_exist": email_get_storage_exist,
    "email_get_storage_disc": email_get_storage_disc,
    "email_get_storage_version": email_get_storage_version,
}


def _register_all_tools() -> None:
    # Storage core subset first (FR15b) — same 4 tools, same annotations, every rendered
    # server bundles.
    for name, wrapper in _STORAGE_WRAPPERS.items():
        annotations = _STORAGE_ANNOTATIONS[name]
        real_description = _STORAGE_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=True,
            ),
            structured_output=True,
        )

    # Email's own curated tools.
    for name, wrapper in _PRODUCT_WRAPPERS.items():
        annotations = _PRODUCT_ANNOTATIONS[name]
        real_description = _PRODUCT_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=annotations["open_world_hint"],
            ),
            structured_output=annotations["structured_output"],
        )


_register_all_tools()


def main() -> None:
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
