"""Auto-generated by Codegen (FR4) from the tracked IR — do not edit by hand.

Regenerate via `run_lifecycle.py --product email --action rebuild` instead of patching this file directly (rubric gate 8: hand-patched generated output is a hard-gate failure).
"""

from __future__ import annotations

from typing import Any, TypedDict

import requests

from aspose_email_mcp._auth import AsposeAuthClient
from aspose_email_mcp._path_resolution import resolve_local_path
from aspose_email_mcp._errors import ToolError, call_with_taxonomy

BASE_URL = "https://api.aspose.cloud/v4.0"


CalendarGetResponse = TypedDict("CalendarGetResponse", {"attachments": list | None, "attendees": list | None, "description": str | None, "endDate": str | None, "endTimeZone": str | None, "flags": list | None, "isDescriptionHtml": bool | None, "location": str | None, "method": str | None, "microsoftBusyStatus": str | None, "microsoftIntendedStatus": str | None, "optionalAttendees": list | None, "organizer": dict | None, "recurrenceString": str | None, "recurrence": dict | None, "reminders": list | None, "sequenceId": str | None, "startDate": str | None, "startTimeZone": str | None, "status": str | None, "summary": str | None, "transparency": str | None, "class": str | None, "microsoftImportance": str | None, "htmlDescription": str | None, "dateTimeStamp": str | None}, total=False)


class CalendarGetListResponse(TypedDict, total=False):
    value: list | None


class CalendarGetAsAlternateResponse(TypedDict, total=False):
    base64Data: str | None
    contentId: str | None
    contentType: dict | None
    headers: dict | None
    baseUri: str | None
    linkedResources: list | None


class ContactGetResponse(TypedDict, total=False):
    associatedPersons: list | None
    attachments: list | None
    companyName: str | None
    computerNetworkName: str | None
    customerId: str | None
    departmentName: str | None
    displayName: str | None
    emailAddresses: list | None
    events: list | None
    fileAs: str | None
    fileAsMapping: str | None
    freeBusyLocation: str | None
    gender: str | None
    givenName: str | None
    governmentIdNumber: str | None
    hobbies: str | None
    initials: str | None
    instantMessengers: list | None
    jobTitle: str | None
    language: str | None
    location: str | None
    middleName: str | None
    nickname: str | None
    notes: str | None
    notesFormat: str | None
    officeLocation: str | None
    organizationalIdNumber: str | None
    phoneNumbers: list | None
    photo: dict | None
    physicalAddresses: list | None
    preferredTextEncoding: str | None
    prefix: str | None
    profession: str | None
    suffix: str | None
    surname: str | None
    urls: list | None


class ContactGetListResponse(TypedDict, total=False):
    value: list | None


class EmailGetListResponse(TypedDict, total=False):
    value: list | None


EmailFromFileResponse = TypedDict("EmailFromFileResponse", {"alternateViews": list | None, "attachments": list | None, "bcc": list | None, "body": str | None, "bodyEncoding": str | None, "bodyType": str | None, "cc": list | None, "date": str | None, "deliveryNotificationOptions": list | None, "from": dict | None, "headers": dict | None, "htmlBody": str | None, "htmlBodyText": str | None, "isBodyHtml": bool | None, "isDraft": bool | None, "isEncrypted": bool | None, "isSigned": bool | None, "linkedResources": list | None, "messageId": str | None, "originalIsTnef": bool | None, "preferredTextEncoding": str | None, "priority": str | None, "readReceiptTo": list | None, "replyToList": list | None, "reversePath": dict | None, "sender": dict | None, "sensitivity": str | None, "subject": str | None, "subjectEncoding": str | None, "timeZoneOffset": int | None, "to": list | None, "xMailer": str | None, "epilogue": str | None, "preamble": str | None}, total=False)


class MapiCalendarGetResponse(TypedDict, total=False):
    attachments: list | None
    billing: str | None
    body: str | None
    bodyHtml: str | None
    bodyRtf: str | None
    bodyType: str | None
    categories: list | None
    companies: list | None
    itemId: str | None
    messageClass: str | None
    mileage: str | None
    recipients: list | None
    sensitivity: str | None
    subject: str | None
    subjectPrefix: str | None
    properties: list | None
    discriminator: str | None
    appointmentCounterProposal: bool | None
    attendees: dict | None
    busyStatus: str | None
    clientIntent: list | None
    endDate: str | None
    endDateTimeZone: dict | None
    isAllDay: bool | None
    keyWords: str | None
    location: str | None
    recurrence: dict | None
    reminderDelta: int | None
    reminderFileParameter: str | None
    reminderSet: bool | None
    sequence: int | None
    startDate: str | None
    startDateTimeZone: dict | None
    uid: str | None
    organizer: dict | None


class MapiContactGetResponse(TypedDict, total=False):
    attachments: list | None
    billing: str | None
    body: str | None
    bodyHtml: str | None
    bodyRtf: str | None
    bodyType: str | None
    categories: list | None
    companies: list | None
    itemId: str | None
    messageClass: str | None
    mileage: str | None
    recipients: list | None
    sensitivity: str | None
    subject: str | None
    subjectPrefix: str | None
    properties: list | None
    discriminator: str | None
    electronicAddresses: dict | None
    events: dict | None
    nameInfo: dict | None
    otherFields: dict | None
    personalInfo: dict | None
    photo: dict | None
    physicalAddresses: dict | None
    professionalInfo: dict | None
    telephones: dict | None


class MapiMessageGetResponse(TypedDict, total=False):
    attachments: list | None
    billing: str | None
    body: str | None
    bodyHtml: str | None
    bodyRtf: str | None
    bodyType: str | None
    categories: list | None
    companies: list | None
    itemId: str | None
    messageClass: str | None
    mileage: str | None
    recipients: list | None
    sensitivity: str | None
    subject: str | None
    subjectPrefix: str | None
    properties: list | None
    discriminator: str | None
    messageBody: str | None
    clientSubmitTime: str | None
    conversationTopic: str | None
    deliveryTime: str | None
    displayBcc: str | None
    displayCc: str | None
    displayName: str | None
    displayNamePrefix: str | None
    displayTo: str | None
    flags: list | None
    headers: dict | None
    internetMessageId: str | None
    messageFormat: str | None
    normalizedSubject: str | None
    readReceiptRequested: bool | None
    replyTo: str | None
    senderAddressType: str | None
    senderEmailAddress: str | None
    senderName: str | None
    senderSmtpAddress: str | None
    sentRepresentingAddressType: str | None
    sentRepresentingEmailAddress: str | None
    sentRepresentingName: str | None
    sentRepresentingSmtpAddress: str | None
    transportMessageHeaders: str | None


class DisposableEmailIsDisposableResponse(TypedDict, total=False):
    value: bool | None


class EmailConfigDiscoverResponse(TypedDict, total=False):
    value: list | None


class ClientAccountGetResponse(TypedDict, total=False):
    host: str | None
    port: int | None
    securityOptions: str | None
    protocolType: str | None
    credentials: dict | None
    cacheFile: dict | None


class ClientAccountGetMultiResponse(TypedDict, total=False):
    receiveAccounts: list | None
    sendAccount: dict | None


class ClientFolderGetListResponse(TypedDict, total=False):
    value: list | None


class ClientMessageFetchResponse(TypedDict, total=False):
    discriminator: str | None


class ClientMessageListResponse(TypedDict, total=False):
    value: list | None


class ClientThreadGetListResponse(TypedDict, total=False):
    value: list | None


class ClientThreadGetMessagesResponse(TypedDict, total=False):
    value: list | None


class AiNameParseResponse(TypedDict, total=False):
    value: list | None


class AiNameGenderizeResponse(TypedDict, total=False):
    value: list | None


class AiNameCompleteResponse(TypedDict, total=False):
    names: list | None
    comments: str | None


class AiNameFormatResponse(TypedDict, total=False):
    name: str | None
    comments: str | None


class AiNameExpandResponse(TypedDict, total=False):
    names: list | None
    comments: str | None


class AiNameMatchResponse(TypedDict, total=False):
    similarity: float | None
    mismatches: list | None


class AiNameParseEmailAddressResponse(TypedDict, total=False):
    value: list | None


class GetFilesListResponse(TypedDict, total=False):
    value: list | None


class StorageExistsResponse(TypedDict, total=False):
    exists: bool | None


class GetDiscUsageResponse(TypedDict, total=False):
    usedSize: int | None
    totalSize: int | None


class GetFileVersionsResponse(TypedDict, total=False):
    value: list | None


def email_get_calendar(auth: AsposeAuthClient, file_name: str, folder: str | None = None, storage: str | None = None) -> CalendarGetResponse:
    'Retrieves the specified iCalendar file from cloud storage.\n\n- **fileName** – required string passed as a query parameter; the exact name of the iCalendar file to fetch from storage.  \n- **folder** – optional string passed as a query parameter; the path to the folder in storage that contains the file (if omitted, the root folder is assumed).  \n- **storage** – optional string passed as a query parameter; the name of the storage service to use (if omitted, the default storage is used).\n\nThe output is the raw contents of the requested iCalendar file returned as a binary stream.'
    params = {k: v for k, v in {"fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/Calendar"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_calendar_list(auth: AsposeAuthClient, folder: str, items_per_page: str | None = None, page_number: str | None = None, storage: str | None = None) -> CalendarGetListResponse:
    'Retrieves a paginated list of iCalendar files stored in a specified folder.  \nfolder (required, string, query): the exact path to the folder in storage from which to list iCalendar files.  \nitemsPerPage (optional, integer, query): maximum number of iCalendar items to return on one page; if omitted the service uses its default page size.  \npageNumber (optional, integer, query): 1‑based index of the page to retrieve; defaults to the first page when omitted.  \nstorage (optional, string, query): name of the storage to query; if omitted the default storage for the account is used.  \nThe output is a JSON object containing an array of the iCalendar entries found in the folder together with pagination metadata such as total count, current page number, and items per page.'
    params = {k: v for k, v in {"folder": folder, "itemsPerPage": items_per_page, "pageNumber": page_number, "storage": storage}.items() if v is not None}
    url = "/email/Calendar/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_calendar_as_alternate(auth: AsposeAuthClient, file_name: str, calendar_action: str, sequence_id: str | None = None, folder: str | None = None, storage: str | None = None) -> CalendarGetAsAlternateResponse:
    'Retrieves an iCalendar file from Aspose Cloud storage and returns its AlternateView representation based on the specified calendar action.  \n\n- **fileName** (required, query, string): exact name of the iCalendar file in storage (e.g.,\u202f“MySchedule.ics”), must be non‑empty.  \n- **calendarAction** (required, query, string): iCalendar METHOD to apply; must be one of the enum values **Create**, **Update**, or **Cancel**.  \n- **sequenceId** (optional, query, string): optional sequence identifier; if supplied it must be a non‑empty string.  \n- **folder** (optional, query, string): path to the folder in storage containing the file; omit to use the root folder.  \n- **storage** (optional, query, string): name of the Aspose Cloud storage to use; omit to use the default storage.  \n\nThe tool outputs a JSON object with two fields: `content` containing the iCalendar data as a UTF‑8 string, and `contentType` set to `"text/calendar"`.'
    params = {k: v for k, v in {"fileName": file_name, "calendarAction": calendar_action, "sequenceId": sequence_id, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/Calendar/as-alternate"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_calendar_as_file(auth: AsposeAuthClient, file_name: str, format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    'This tool fetches a calendar document from Aspose Cloud storage, converts it to the specified format, and returns the resulting file.\n\n- **fileName** – required, string, query parameter. The exact name of the calendar file stored in the cloud (including its current extension).  \n- **format** – required, string, query parameter. Target file format; must be either `Ics` or `Msg`.  \n- **storage** – optional, string, query parameter. Name of the Aspose Cloud storage to read from; if omitted the default storage is used.  \n- **folder** – optional, string, query parameter. Path to the folder within the storage that contains the file; if omitted the root folder is assumed.\n\nThe tool outputs the converted calendar as binary file data (the file content in the chosen format).'
    params = {k: v for k, v in {"fileName": file_name, "format": format, "storage": storage, "folder": folder}.items() if v is not None}
    url = "/email/Calendar/as-file"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_contact(auth: AsposeAuthClient, format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> ContactGetResponse:
    'The tool retrieves a contact document from the specified storage location.\n\n- **format** – query parameter, string, required; must be one of the following values: `VCard`, `WebDav`, `Msg`.  \n- **fileName** – query parameter, string, required; the exact name of the contact file to retrieve.  \n- **folder** – query parameter, string, optional; the path to the folder in storage that contains the file (if omitted the root folder is assumed).  \n- **storage** – query parameter, string, optional; the name of the storage service to use (if omitted the default storage is used).\n\nThe output is the raw binary content of the requested contact file in the specified format.'
    params = {k: v for k, v in {"format": format, "fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/Contact"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_contact_list(auth: AsposeAuthClient, format: str, folder: str | None = None, storage: str | None = None, items_per_page: str | None = None, page_number: str | None = None) -> ContactGetListResponse:
    'Retrieves a list of email contacts from a specified folder and storage using the given contact document format.  \nformat (query, string, required): contact document format; allowed values are **VCard**, **WebDav**, **Msg** (case‑sensitive).  \nfolder (query, string, optional): path to the folder in storage that contains the contacts; if omitted the root folder is used.  \nstorage (query, string, optional): name of the storage to query; if omitted the default storage is used.  \nitemsPerPage (query, integer, optional): maximum number of contacts to return on a single page; must be a positive integer.  \npageNumber (query, integer, optional): 1‑based index of the page to retrieve; must be a positive integer.  \nReturns a JSON object containing an array of contact objects (each with fields such as name, email, etc.) and pagination metadata including total count, itemsPerPage, and pageNumber.'
    params = {k: v for k, v in {"format": format, "folder": folder, "storage": storage, "itemsPerPage": items_per_page, "pageNumber": page_number}.items() if v is not None}
    url = "/email/Contact/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_contact_as_file(auth: AsposeAuthClient, file_name: str, to_format: str, from_format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    'Converts a contact document stored in Aspose Cloud from one format to another and returns the resulting file as binary data.  \n- `fileName` (query string, required): the name of the contact file in storage, including its extension.  \n- `toFormat` (query string, required): target format for the conversion; must be one of the enum values `VCard`, `WebDav`, or `Msg`.  \n- `fromFormat` (query string, required): source format of the existing file; must be one of the enum values `VCard`, `WebDav`, or `Msg`.  \n- `storage` (query string, optional): name of the Aspose Cloud storage where the file is located; if omitted the default storage is used.  \n- `folder` (query string, optional): path to the folder within the specified storage that contains the file; if omitted the root folder is assumed.  \nThe tool returns the binary contents of the converted contact file as a downloadable stream, accompanied by appropriate MIME type and content‑disposition metadata.'
    params = {k: v for k, v in {"fileName": file_name, "toFormat": to_format, "fromFormat": from_format, "storage": storage, "folder": folder}.items() if v is not None}
    url = "/email/Contact/as-file"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_list(auth: AsposeAuthClient, format: str, folder: str | None = None, storage: str | None = None, items_per_page: str | None = None, page_number: str | None = None) -> EmailGetListResponse:
    'The tool retrieves a list of email files stored in a specified folder of Aspose Cloud storage.  \n\n- format: required string query parameter; must be one of the enum values\u202fEml,\u202fMsg,\u202fMsgUnicode,\u202fMhtml,\u202fHtml,\u202fTnef,\u202fOft.  \n- folder: optional string query parameter; path to the folder in storage from which to list email files.  \n- storage: optional string query parameter; name of the Aspose Cloud storage to use.  \n- itemsPerPage: optional integer query parameter; maximum number of email file entries to return on a single page.  \n- pageNumber: optional integer query parameter; the page index (starting at 1) to retrieve when pagination is applied.  \n\nThe output is a JSON object containing an array of email file names (strings) from the requested folder, optionally accompanied by pagination metadata such as total count, itemsPerPage, and pageNumber.'
    params = {k: v for k, v in {"format": format, "folder": folder, "storage": storage, "itemsPerPage": items_per_page, "pageNumber": page_number}.items() if v is not None}
    url = "/email/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_as_file(auth: AsposeAuthClient, file_name: str, format: str, storage: str | None = None, folder: str | None = None) -> dict[str, Any]:
    'The tool fetches an email document from Aspose Cloud storage, converts it to a specified format, and returns the result as a downloadable file.  \n\n- **fileName** – required query parameter; string; the exact name of the email file stored in the cloud.  \n- **format** – required query parameter; string; must be one of the supported values: `Eml`, `Msg`, `MsgUnicode`, `Mhtml`, `Html`, `Tnef`, `Oft`.  \n- **storage** – optional query parameter; string; the name of the storage service where the file is located (if omitted, the default storage is used).  \n- **folder** – optional query parameter; string; the path to the folder within the storage that contains the email file (if omitted, the root folder is assumed).  \n\nThe tool outputs a binary file stream containing the converted email in the requested format.'
    params = {k: v for k, v in {"fileName": file_name, "format": format, "storage": storage, "folder": folder}.items() if v is not None}
    url = "/email/as-file"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_extract_properties(auth: AsposeAuthClient, content_filename: str, source_format: str, content_base64: str | None = None, dry_run: bool = False) -> EmailFromFileResponse:
    'This tool converts an email document file into a structured email model representation.  \nformat: a required query string parameter specifying the email file format; valid values are Eml, Msg, MsgUnicode, Mhtml, Html, Tnef, and Oft.  \nFile: a required form‑data file parameter containing the binary email document to be converted.  \nThe output is a JSON object representing the parsed email, including fields such as subject, body, sender, recipients, attachments, and related metadata.'
    params = {k: v for k, v in {"format": source_format}.items() if v is not None}
    url = "/email/from-file"
    if dry_run:
        resolve_local_path(content_filename) if content_base64 is None else None
        return {"dry_run": True, "would_upload": content_filename}
    if content_base64 is not None:
        import base64 as _base64
        content = _base64.b64decode(content_base64)
    else:
        local_path = resolve_local_path(content_filename)
        content = local_path.read_bytes()
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header(), "Content-Type": "application/octet-stream"},
        data=content,
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_convert_file(auth: AsposeAuthClient, content_filename: str, source_format: str, target_format: str, content_base64: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    'It converts an uploaded email document from a given source format to a specified target format and returns the resulting file.  \n\n- **fromFormat** (required, query string): must be exactly one of the following values – `Eml`, `Msg`, `MsgUnicode`, `Mhtml`, `Html`, `Tnef`, `Oft`; indicates the format of the input email file.  \n- **toFormat** (required, query string): must be exactly one of the following values – `Eml`, `Msg`, `MsgUnicode`, `Mhtml`, `Html`, `Tnef`, `Oft`; indicates the desired output format for the converted email file.  \n- **File** (required, form‑data file): the binary email document to be converted; supplied as a file upload in the request body.  \n\nThe tool returns a binary response containing the converted email file, with the appropriate content‑type header matching the requested `toFormat`.'
    params = {k: v for k, v in {"fromFormat": source_format, "toFormat": target_format}.items() if v is not None}
    url = "/email/convert"
    if content_base64 is not None:
        import base64 as _base64
        content = _base64.b64decode(content_base64)
    else:
        local_path = resolve_local_path(content_filename)
        content = local_path.read_bytes()
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header(), "Content-Type": "application/octet-stream"},
        data=content,
        timeout=30.0,
    ))
    if return_base64:
        import base64 as _base64
        return {"content_base64": _base64.b64encode(response.content).decode("ascii")}
    local_path = resolve_local_path(output_filename or "converted_output", is_output=True)
    local_path.write_bytes(response.content)
    return {"Status": "OK", "local_path": str(local_path)}


def email_get_mapi_calendar(auth: AsposeAuthClient, file_name: str, folder: str | None = None, storage: str | None = None) -> MapiCalendarGetResponse:
    'This tool retrieves a MAPI calendar file from Aspose Cloud storage.  \n\n- fileName (required, query string): exact name of the calendar file to fetch.  \n- folder (optional, query string): path to the folder containing the file; if omitted the root folder is assumed.  \n- storage (optional, query string): name of the storage service to use; if omitted the account’s default storage is used.  \n\nThe tool returns the raw binary content of the requested MAPI calendar document.'
    params = {k: v for k, v in {"fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/MapiCalendar"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_mapi_contact(auth: AsposeAuthClient, format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> MapiContactGetResponse:
    'Retrieves a MAPI contact document from Aspose Cloud storage in the format you specify.  \n\n- **format** – query parameter, string, required; must be one of the enum values\u202f`VCard`, `WebDav`, or `Msg`.  \n- **fileName** – query parameter, string, required; the exact name of the contact document file to retrieve.  \n- **folder** – query parameter, string, optional; the path to the folder in the storage where the file resides (omit or leave empty for the root folder).  \n- **storage** – query parameter, string, optional; the name of the storage service to query (if omitted the default storage is used).  \n\nThe tool returns the contact document’s raw binary content (the file data in the selected format) as the response payload.'
    params = {k: v for k, v in {"format": format, "fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/MapiContact"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_mapi_message(auth: AsposeAuthClient, format: str, file_name: str, folder: str | None = None, storage: str | None = None) -> MapiMessageGetResponse:
    'This tool retrieves a specific email document stored as a MAPI message from Aspose Cloud.  \n\n- **format** – required query parameter; string; must be exactly one of the following values: Eml, Msg, MsgUnicode, Mhtml, Html, Tnef, Oft.  \n- **fileName** – required query parameter; string; the name of the email document file to retrieve.  \n- **folder** – optional query parameter; string; the path to the folder in storage where the file is located.  \n- **storage** – optional query parameter; string; the name of the storage service to use.  \n\nThe output is the raw byte content of the requested email document in the specified format.'
    params = {k: v for k, v in {"format": format, "fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/MapiMessage"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_disposable_is_disposable(auth: AsposeAuthClient, address: str) -> DisposableEmailIsDisposableResponse:
    'This tool determines whether a given email address is a disposable (temporary) address.  \naddress: required query parameter, string, must be a syntactically valid email address in the form local-part@domain.  \nThe output is a JSON object containing a single boolean field named “isDisposable” that is true if the address is disposable and false otherwise.'
    params = {k: v for k, v in {"address": address}.items() if v is not None}
    url = "/email/disposable/is-disposable"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_config_discover(auth: AsposeAuthClient, address: str, fast_processing: bool | None = None) -> EmailConfigDiscoverResponse:
    'The tool discovers email server configuration settings for a given email address without validating the discovered accounts.  \n- **address** (query, required, string): the email address to discover; must be supplied in a standard email format (e.g., user@example.com).  \n- **fastProcessing** (query, optional, boolean): if true, all discovery systems are run in parallel and the first discovered result is returned; acceptable values are `true` or `false`.  \nThe output is a JSON object containing the discovered email configuration details for the first matching account.'
    params = {k: v for k, v in {"address": address, "fastProcessing": fast_processing}.items() if v is not None}
    url = "/email/config/discover"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_client_account(auth: AsposeAuthClient, file_name: str, folder: str | None = None, storage: str | None = None) -> ClientAccountGetResponse:
    'Retrieves the email client account configuration stored at the specified location.  \n\n- fileName: required string query parameter; the exact name of the account file on storage (e.g., “account.json”).  \n- folder: optional string query parameter; the path to the folder containing the file on storage, without a trailing slash.  \n- storage: optional string query parameter; the name of the storage service to use if multiple storages are configured.  \n\nReturns a JSON object representing the stored email client account, containing the account’s properties such as email address, display name, server settings, and other configuration fields.'
    params = {k: v for k, v in {"fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/client/account"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_client_account_multi(auth: AsposeAuthClient, file_name: str, folder: str | None = None, storage: str | None = None) -> ClientAccountGetMultiResponse:
    'The tool fetches a *.multi.account email client file from Aspose Cloud storage.  \nfileName (required, string, query): exact name of the file on storage; must end with the extension “.multi.account”.  \nfolder (optional, string, query): path to the folder in storage containing the file; if omitted the root folder is assumed.  \nstorage (optional, string, query): name of the storage to use; if omitted the default storage is used.  \nThe tool returns the raw binary content of the requested .multi.account file.'
    params = {k: v for k, v in {"fileName": file_name, "folder": folder, "storage": storage}.items() if v is not None}
    url = "/email/client/account/multi"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_delete_client_folder(auth: AsposeAuthClient, request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    'Deletes a specific folder from a user\'s email account via the Aspose Cloud Email API.  \n\nParameter\u202f`request`\u202f– required body JSON object with exactly one field:  \n- **folder**\u202f(string, required): the full path of the folder to be removed (e.g., `"Inbox/Newsletters"`); must be a non‑empty string that identifies an existing folder in the account. No other fields are accepted.  \n\nThe tool returns a JSON object: on success the response body is empty (`{}`); on failure it contains an **errorCode** (integer) and an **errorMessage** (string) describing the problem.'
    params = {}
    url = "/email/client/folder"
    if dry_run:
        return {"dry_run": True, "operation": "ClientFolderDelete"}
    response = call_with_taxonomy(lambda: requests.delete(
        f"{BASE_URL}{url}",
        params=params,
        json=request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_client_folder_list(auth: AsposeAuthClient, account: str, storage: str | None = None, account_storage_folder: str | None = None, parent_folder: str | None = None) -> ClientFolderGetListResponse:
    'The tool retrieves the list of folders (or sub‑folders) for a specified email account.  \n- account: required string supplied as a query parameter, the email account identifier.  \n- storage: optional string supplied as a query parameter, name of the storage where the account file is located.  \n- accountStorageFolder: optional string supplied as a query parameter, path in the storage to the folder containing the account file.  \n- parentFolder: optional string supplied as a query parameter, path of the folder whose immediate subfolders should be listed.  \nThe output is a JSON object containing an array of folder information objects representing each retrieved folder.'
    params = {k: v for k, v in {"account": account, "storage": storage, "accountStorageFolder": account_storage_folder, "parentFolder": parent_folder}.items() if v is not None}
    url = "/email/client/folder/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_create_client_message(auth: AsposeAuthClient, request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    'Sends an email through the Aspose Cloud email client‑message endpoint.  \n\nrequest (required, body, JSON object):  \n- sender (string, required): email address of the sender.  \n- to (array of strings, required): list of recipient email addresses.  \n- cc (array of strings, optional): list of carbon‑copy recipient email addresses.  \n- bcc (array of strings, optional): list of blind‑carbon‑copy recipient email addresses.  \n- subject (string, required): subject line of the email.  \n- body (string, required): main content of the email.  \n- isHtml (boolean, optional): true if the body is HTML; defaults to false.  \n- attachments (array of objects, optional): each object must contain  \n  • fileName (string, required): name of the attached file,  \n  • contentBase64 (string, required): file data encoded in base64,  \n  • mimeType (string, required): MIME type of the file.  \n\nReturns a JSON object containing the send result with the fields: messageId (string), status (string, e.g., "Sent" or "Failed"), errorCode (integer, optional, present only on failure), and errorMessage (string, optional, present only on failure).'
    params = {}
    url = "/email/client/message"
    if dry_run:
        return {"dry_run": True, "operation": "ClientMessageSend"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        json=request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_client_message(auth: AsposeAuthClient, message_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, type: str | None = None, format: str | None = None) -> ClientMessageFetchResponse:
    'Fetch a specific email message from a given email account.  \n\n- **messageId** – required string supplied as a query parameter; the unique identifier of the message to retrieve.  \n- **account** – required string supplied as a query parameter; the email account address or identifier containing the message.  \n- **folder** – optional string supplied as a query parameter; the folder name within the account (e.g., “Inbox”, “Sent”) required for protocols such as IMAP.  \n- **storage** – optional string supplied as a query parameter; the name of the Aspose Cloud storage where the account file resides.  \n- **accountStorageFolder** – optional string supplied as a query parameter; the path to the folder inside the specified storage that holds the account file.  \n- **type** – optional string supplied as a query parameter; determines the representation format of the returned message and must be one of the enum values **Dto**, **Mapi**, or **Base64**.  \n- **format** – optional string supplied as a query parameter; applicable only when **type** is set to **Base64** and must be one of **Eml**, **Msg**, **MsgUnicode**, **Mhtml**, **Html**, **Tnef**, or **Oft**.  \n\nThe tool returns a JSON object containing the fetched email in the requested representation: an EmailDto object when **type**=Dto, a MapiMessageDto object when **type**=Mapi, or a Base64‑encoded string (with the specified format) when **type**=Base64.'
    params = {k: v for k, v in {"messageId": message_id, "account": account, "folder": folder, "storage": storage, "accountStorageFolder": account_storage_folder, "type": type, "format": format}.items() if v is not None}
    url = "/email/client/message"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_delete_client_message(auth: AsposeAuthClient, request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    'Deletes a specific email message from the client mailbox.  \n- request: required, body parameter, type\u202f=\u202fJSON object conforming to the DeleteMessageRequest schema defined by the API (the object must contain the fields required by that schema).  \nThe tool returns the API response, which on successful deletion is typically an empty JSON object (or the corresponding HTTP status indicating success).'
    params = {}
    url = "/email/client/message"
    if dry_run:
        return {"dry_run": True, "operation": "ClientMessageDelete"}
    response = call_with_taxonomy(lambda: requests.delete(
        f"{BASE_URL}{url}",
        params=params,
        json=request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_client_message_file(auth: AsposeAuthClient, message_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, format: str | None = None) -> dict[str, Any]:
    'Fetches a single email message from a specified account and returns it as a downloadable file in the chosen format.  \n\n- messageId: required string query parameter – unique identifier of the email message to retrieve.  \n- account: required string query parameter – name of the email account containing the message.  \n- folder: optional string query parameter – folder within the account to search (must be set for protocols such as IMAP).  \n- storage: optional string query parameter – name of the Aspose Cloud storage where the account file is located.  \n- accountStorageFolder: optional string query parameter – path to the folder in the specified storage that holds the account file.  \n- format: optional string query parameter – desired output file format; must be one of: Eml, Msg, MsgUnicode, Mhtml, Html, Tnef, Oft.  \n\nThe tool outputs the requested email message as a binary file payload (byte array) together with metadata indicating its filename and MIME type.'
    params = {k: v for k, v in {"messageId": message_id, "account": account, "folder": folder, "storage": storage, "accountStorageFolder": account_storage_folder, "format": format}.items() if v is not None}
    url = "/email/client/message/file"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_client_message_list(auth: AsposeAuthClient, folder: str, account: str, query_string: str | None = None, storage: str | None = None, account_storage_folder: str | None = None, recursive: bool | None = None, type: str | None = None, format: str | None = None) -> ClientMessageListResponse:
    'Retrieves a list of email messages from a specified folder in a given email account, optionally filtered by a query string and returned in the requested format.  \n\n- **folder** – query parameter, **string**, **required**: the folder path/name within the email account to read messages from.  \n- **account** – query parameter, **string**, **required**: the identifier of the email account containing the folder.  \n- **queryString** – query parameter, **string**, **optional**: a MailQuery search string used to filter the returned messages.  \n- **storage** – query parameter, **string**, **optional**: the name of the storage where the account file is located.  \n- **accountStorageFolder** – query parameter, **string**, **optional**: the folder within the storage that contains the account file.  \n- **recursive** – query parameter, **boolean**, **optional**: if true, search includes sub‑folders recursively; defaults to false when omitted.  \n- **type** – query parameter, **string**, **optional**: representation of each message; allowed values are **Dto**, **Mapi**, **Base64**; defaults to **Dto** when omitted.  \n- **format** – query parameter, **string**, **optional**: required only when **type** is **Base64**; allowed values are **Eml**, **Msg**, **MsgUnicode**, **Mhtml**, **Html**, **Tnef**, **Oft**; ignored for other **type** values.  \n\nReturns a JSON array where each element is a message in the selected representation (an EmailDto object, a MapiMessageDto object, or a Base64‑encoded file string).'
    params = {k: v for k, v in {"folder": folder, "account": account, "queryString": query_string, "storage": storage, "accountStorageFolder": account_storage_folder, "recursive": recursive, "type": type, "format": format}.items() if v is not None}
    url = "/email/client/message/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_client_thread_list(auth: AsposeAuthClient, folder: str, account: str, storage: str | None = None, account_storage_folder: str | None = None, update_folder_cache: bool | None = None, messages_cache_limit: str | None = None) -> ClientThreadGetListResponse:
    'The tool retrieves a list of email message threads from a specified folder in a given email account, returning only partial information for each message (no body or full fields).  \n\n- **folder** – required query parameter of type string; the name or path of the folder within the email account to enumerate threads from.  \n- **account** – required query parameter of type string; the identifier of the email account containing the folder.  \n- **storage** – optional query parameter of type string; the name of the storage location where the account file is stored.  \n- **accountStorageFolder** – optional query parameter of type string; the path to the folder in the specified storage that holds the account file.  \n- **updateFolderCache** – optional query parameter of type boolean; if true, the operation fetches new messages and updates the threads cache for the folder, if false it returns threads only from the existing cache without contacting the email server.  \n- **messagesCacheLimit** – optional query parameter of type integer; defines the maximum number of messages to retain in the cache when CacheFile is used (ignored for accounts without cache limits).  \n\nThe output is a JSON object containing a `threads` array, where each element is a thread summary object with its identifier and partially‑fetched message metadata.'
    params = {k: v for k, v in {"folder": folder, "account": account, "storage": storage, "accountStorageFolder": account_storage_folder, "updateFolderCache": update_folder_cache, "messagesCacheLimit": messages_cache_limit}.items() if v is not None}
    url = "/email/client/thread/list"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_client_thread_messages(auth: AsposeAuthClient, thread_id: str, account: str, folder: str | None = None, storage: str | None = None, account_storage_folder: str | None = None) -> ClientThreadGetMessagesResponse:
    'Retrieves all messages that belong to a given email thread, optionally scoped to a specific folder or storage location.  \n\n- **threadId** – required query parameter, type **string**; the unique identifier of the email thread to fetch.  \n- **account** – required query parameter, type **string**; the email account name from which to retrieve the thread.  \n- **folder** – optional query parameter, type **string**; the name of the folder within the account to search for the thread (if omitted, the default folder is used).  \n- **storage** – optional query parameter, type **string**; the name of the storage service where the account file is located.  \n- **accountStorageFolder** – optional query parameter, type **string**; the path to the folder in the specified storage that contains the account file.  \n\nReturns a JSON object containing an array of fully‑fetched message objects representing each email in the requested thread.'
    params = {k: v for k, v in {"threadId": thread_id, "account": account, "folder": folder, "storage": storage, "accountStorageFolder": account_storage_folder}.items() if v is not None}
    url = "/email/client/thread/messages"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_delete_client_thread(auth: AsposeAuthClient, request: dict[str, Any], dry_run: bool = False) -> dict[str, Any]:
    'The tool deletes an email thread identified by its ID, permanently removing all messages that belong to that thread.  \nParameters:\u202frequest\u202f(required, body, JSON object) – a DeleteEmailThreadRequest object that must contain a string field **threadId** specifying the identifier of the thread to delete.  \nThe tool returns the API’s HTTP response, typically a JSON object confirming the deletion or providing error details.'
    params = {}
    url = "/email/client/thread"
    if dry_run:
        return {"dry_run": True, "operation": "ClientThreadDelete"}
    response = call_with_taxonomy(lambda: requests.delete(
        f"{BASE_URL}{url}",
        params=params,
        json=request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_ai_name_parse(auth: AsposeAuthClient, name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameParseResponse:
    'Parse a personal name into its constituent components (e.g., given name, middle name, surname, title, etc.) using the Aspose Cloud AiName service.  \n- name (query, string, required): the full name to parse; must be a non‑empty UTF‑8 string.  \n- language (query, string, optional): an ISO‑639 language identifier, either a two‑letter code (e.g., “it”) or a three‑letter code (e.g., “ita”); defaults to English if omitted.  \n- location (query, string, optional): an ISO‑3166‑1 alpha‑2 country code indicating geographic context (e.g., “FR”); must be exactly two uppercase letters if provided.  \n- encoding (query, string, optional): the character encoding name for the input (e.g., “UTF-8”); any encoding recognized by the service is allowed.  \n- script (query, string, optional): an ISO‑15924 script code indicating the writing system (e.g., “Latn”); must be a valid script identifier.  \n- style (query, string, optional): the name writing style; must be one of the enum values “Formal”, “Informal”, “Legal”, or “Academic”.  \nThe tool returns a JSON object containing parsed name fields such as `givenName`, `middleName`, `surname`, `title`, `prefix`, `suffix`, and associated confidence scores for each component.'
    params = {k: v for k, v in {"name": name, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/parse"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_genderize(auth: AsposeAuthClient, name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameGenderizeResponse:
    'This tool invokes the Aspose Cloud AI Name genderize endpoint to infer the most likely gender for a given personal name.  \n- **name**: query string, required – the name to be genderized; must be a non‑empty text value.  \n- **language**: query string, optional – an ISO‑639 language code, either the two‑letter (639‑1) or three‑letter (639‑3) form (e.g., “it” or “ita”).  \n- **location**: query string, optional – an ISO‑3166 two‑letter country code indicating geographic context (e.g., “FR”).  \n- **encoding**: query string, optional – a valid character‑encoding name supported by the service (for example “UTF-8”).  \n- **script**: query string, optional – an ISO‑15924 script name identifying the writing system (e.g., “Latn”).  \n- **style**: query string, optional – must be one of the enumerated values: Formal, Informal, Legal, Academic.  \nThe output is a JSON object containing the detected gender (such as “Male” or “Female”) along with any confidence or probability information returned by the API.'
    params = {k: v for k, v in {"name": name, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/genderize"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_complete(auth: AsposeAuthClient, name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameCompleteResponse:
    'This tool returns up to\u202fk suggested full names that best complete the supplied name prefix.  \n\nk: optional integer query parameter – the number of name candidates to return; must be a positive integer (greater than\u202f0); if omitted the service applies its own default.  \n\nname: required string query parameter – the partial name to be completed.  \n\nlanguage: optional string query parameter – an ISO‑639 language code, either two‑letter (e.g., "it") or three‑letter (e.g., "ita").  \n\nlocation: optional string query parameter – an ISO‑3166 two‑letter country code (e.g., "FR").  \n\nencoding: optional string query parameter – a character‑encoding name such as "UTF-8".  \n\nscript: optional string query parameter – a writing‑system code that begins with an ISO‑15924 script identifier (e.g., "Latn").  \n\nstyle: optional string query parameter – the name‑writing style; must be exactly one of the case‑sensitive values: Formal, Informal, Legal, Academic.  \n\nThe tool outputs a JSON object containing a field named “candidates” that is an array of strings, each string being one of the proposed completed names.'
    params = {k: v for k, v in {"name": name, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/complete"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_format(auth: AsposeAuthClient, name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, format: str | None = None, style: str | None = None) -> AiNameFormatResponse:
    'Formats a given person’s name into the correct case and order using optional language, region, script, style, and formatting settings, and returns the formatted name.  \n\n- **name** (query, string, required): the raw name to be formatted.  \n- **language** (query, string, optional): an ISO‑639 language code, either two‑letter (639‑1) or three‑letter (639‑3) form such as “it” or “ita”.  \n- **location** (query, string, optional): an ISO‑3166 alpha‑2 country code indicating geographic context, e.g., “FR”.  \n- **encoding** (query, string, optional): the name of the character encoding to use (e.g., “UTF-8”).  \n- **script** (query, string, optional): a writing‑system code that must start with a valid ISO‑15924 script name (e.g., “Latn”).  \n- **format** (query, string, optional): either one of the predefined format identifiers  \n\u202f\u202f`default`, `FN+LN`, `title+FN+LN`, `FN+MN+LN`, `title+FN+MN+LN`, `FN+MI+LN`, `title+FN+MI+LN`, `LN`, `title+LN`, `LN+FN+MN`, `LN+title+FN+MN`, `LN+FN+MI`, `LN+title+FN+MI` (corresponding to the patterns shown in the specification), or a custom format string composed of the placeholders `%t`, `%F`, `%f`, `%M`, `%m`, `%N`, `%L`, `%l`, `%p`. If omitted, the default pattern `%t%F%m%N%L%p` is applied.  \n- **style** (query, string, optional): the writing style to apply; must be one of the enum values **Formal**, **Informal**, **Legal**, or **Academic**.  \n\nThe tool outputs a JSON object with a single field `formattedName` (string) that contains the name rendered according to the supplied options.'
    params = {k: v for k, v in {"name": name, "language": language, "location": location, "encoding": encoding, "script": script, "format": format, "style": style}.items() if v is not None}
    url = "/email/AiName/format"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_expand(auth: AsposeAuthClient, name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameExpandResponse:
    'This tool expands a given personal name into a list of possible alternative spellings or forms based on optional language, location, encoding, script, and style settings.  \n\nParameters:  \n- **name** (required, query string) – the name to expand.  \n- **language** (optional, query string) – an ISO‑639 language code, either two‑letter (e.g., “it”) or three‑letter (e.g., “ita”).  \n- **location** (optional, query string) – an ISO‑3166 two‑letter country code such as “FR”.  \n- **encoding** (optional, query string) – a character encoding name (e.g., “UTF-8”).  \n- **script** (optional, query string) – an ISO‑15924 script code (e.g., “Latn”).  \n- **style** (optional, query string) – the name‑writing style; must be exactly one of: Formal, Informal, Legal, Academic.  \n\nThe output is a JSON object containing an array (e.g., “expandedNames”) that lists each generated alternative name as a string.'
    params = {k: v for k, v in {"name": name, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/expand"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_match(auth: AsposeAuthClient, name: str, other_name: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameMatchResponse:
    'This tool compares two personal names and returns a similarity assessment.\n\n- **name** – required query string: the first name to be compared.  \n- **otherName** – required query string: the second name to be compared.  \n- **language** – optional query string: an ISO‑639 language code, either the two‑letter (639‑1) form (e.g., “it”) or the three‑letter (639‑3) form (e.g., “ita”).  \n- **location** – optional query string: an ISO‑3166 two‑letter country code indicating geographic context (e.g., “FR”).  \n- **encoding** – optional query string: the name’s character encoding name (any valid encoding identifier, such as “UTF-8”).  \n- **script** – optional query string: the writing‑system code, starting with the ISO‑15924 script name (e.g., “Latn”).  \n- **style** – optional query string: the name‑writing style; must be one of the following exact values: **Formal**, **Informal**, **Legal**, **Academic**.\n\nThe output is a JSON object containing a numeric similarity score between 0 and 1 and a boolean field indicating whether the two names are considered a match.'
    params = {k: v for k, v in {"name": name, "otherName": other_name, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/match"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_ai_name_parse_email_address(auth: AsposeAuthClient, email_address: str, language: str | None = None, location: str | None = None, encoding: str | None = None, script: str | None = None, style: str | None = None) -> AiNameParseEmailAddressResponse:
    'This tool extracts a person’s name from a given email address using Aspose Cloud’s AiName parsing service.  \n\n- **emailAddress** (required, string, query): a valid email address to parse, e.g., “john.doe@example.com”.  \n- **language** (optional, string, query): an ISO‑639 language code, either the two‑letter 639‑1 form or the three‑letter 639‑3 form (e.g., “it” or “ita”).  \n- **location** (optional, string, query): an ISO‑3166 two‑letter country code representing a geographic location (e.g., “FR”).  \n- **encoding** (optional, string, query): the name of the character encoding to use (e.g., “UTF-8”).  \n- **script** (optional, string, query): an ISO‑15924 writing‑system code that identifies the script (e.g., “Latn”).  \n- **style** (optional, string, query): the desired name writing style; must be one of the following exact values: “Formal”, “Informal”, “Legal”, “Academic”.  \n\nThe tool returns a JSON object containing the parsed name components (such as given name, middle name, and surname) together with any inferred language, location, encoding, script, or style metadata.'
    params = {k: v for k, v in {"emailAddress": email_address, "language": language, "location": location, "encoding": encoding, "script": script, "style": style}.items() if v is not None}
    url = "/email/AiName/parse-email-address"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_storage_file(auth: AsposeAuthClient, path: str, storage_name: str | None = None, version_id: str | None = None) -> dict[str, Any]:
    'The tool downloads a file from Aspose Cloud Email storage and returns the file’s binary contents.  \n\n- **path** – required string in the URL path; must be the full storage path of the file and start with “/”, e.g. “/folder/file.ext”.  \n- **storageName** – optional string supplied as a query parameter; specifies the name of the storage to use.  \n- **versionId** – optional string supplied as a query parameter; specifies the version ID of the file to retrieve.  \n\nThe output is the raw byte stream of the requested file (the file’s binary data).'
    params = {k: v for k, v in {"storageName": storage_name, "versionId": version_id}.items() if v is not None}
    url = f"/email/storage/file/{path}"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_delete_storage_file(auth: AsposeAuthClient, path: str, storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Deletes a file stored in Aspose Cloud at the specified path.  \n- path: required string, supplied as the URL path segment; must be a valid file path beginning with “/” (e.g., “/folder/file.ext”).  \n- storageName: optional string query parameter; the name of the storage to use; if omitted the default storage for the account is used.  \n- versionId: optional string query parameter; the identifier of a specific file version to delete; if omitted the latest version is removed.  \nThe tool returns a JSON object containing the HTTP statusCode (integer) and, on failure, an error message string; on success the object includes only the statusCode (e.g., 200).'
    params = {k: v for k, v in {"storageName": storage_name, "versionId": version_id}.items() if v is not None}
    url = f"/email/storage/file/{path}"
    if dry_run:
        return {"dry_run": True, "operation": "DeleteFile"}
    response = call_with_taxonomy(lambda: requests.delete(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_update_storage_file_copy(auth: AsposeAuthClient, src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Copies a file from a specified source path in Aspose Cloud storage to a given destination path, optionally using different source or destination storages or a particular file version.  \nsrcPath (path, string, required): must start with “/” and be a valid storage path, e.g., “/folder/file.ext”.  \ndestPath (query, string, required): must start with “/” and be a valid storage path that includes the target file name.  \nsrcStorageName (query, string, optional): name of the storage where the source file resides; if omitted the default storage is used.  \ndestStorageName (query, string, optional): name of the storage where the file should be copied; if omitted the default storage is used.  \nversionId (query, string, optional): identifier of the specific file version to copy; if omitted the latest version is copied.  \nThe tool returns a JSON object containing two fields:\u202fstatusCode\u202f(integer) indicating the HTTP response code and\u202fmessage\u202f(string) providing a success confirmation or error description.'
    params = {k: v for k, v in {"destPath": dest_path, "srcStorageName": src_storage_name, "destStorageName": dest_storage_name, "versionId": version_id}.items() if v is not None}
    url = f"/email/storage/file/copy/{src_path}"
    if dry_run:
        return {"dry_run": True, "operation": "CopyFile"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_update_storage_file_move(auth: AsposeAuthClient, src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, version_id: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Moves a file from a source location to a destination location within Aspose Cloud storage, optionally specifying different storage names or a file version.  \nsrcPath (path, string, required): the full source file path, e.g.\u202f`/src.ext`.  \ndestPath (query, string, required): the full destination file path, e.g.\u202f`/dest.ext`.  \nsrcStorageName (query, string, optional): the name of the storage that contains the source file; omitted to use the default storage.  \ndestStorageName (query, string, optional): the name of the storage where the file should be moved; omitted to use the default storage.  \nversionId (query, string, optional): identifier of a specific file version to move; if omitted the latest version is moved.  \nReturns a JSON object with the HTTP status code, a boolean indicating success, and a message describing the outcome.'
    params = {k: v for k, v in {"destPath": dest_path, "srcStorageName": src_storage_name, "destStorageName": dest_storage_name, "versionId": version_id}.items() if v is not None}
    url = f"/email/storage/file/move/{src_path}"
    if dry_run:
        return {"dry_run": True, "operation": "MoveFile"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_storage_folder(auth: AsposeAuthClient, path: str, storage_name: str | None = None) -> GetFilesListResponse:
    'Retrieves a list of all files and sub‑folders that exist inside a given email storage folder. Parameters: path – string, required, inserted into the URL path as {path}, must represent a valid folder path (e.g. "/folder"); storageName – string, optional, supplied as a query parameter to select the storage name. Returns a JSON object whose main property is an array (e.g., “value”) of file/folder descriptor objects each containing fields such as Name, IsFolder, Size, and ModifiedDate.'
    params = {k: v for k, v in {"storageName": storage_name}.items() if v is not None}
    url = f"/email/storage/folder/{path}"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_update_storage_folder(auth: AsposeAuthClient, path: str, storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Creates a new folder in the specified Aspose Cloud email storage at the given path.  \n\npath: required string supplied in the URL path, representing the folder hierarchy to create (e.g., “folder_1/folder_2/”); must be URL‑encoded if it contains special characters.  \n\nstorageName: optional string supplied as a query parameter named storageName, indicating the storage name to use; if omitted the default storage is applied.  \n\nThe tool returns the raw HTTP response from the Aspose Cloud service, including the status code and any JSON body that reports the result of the folder‑creation request.'
    params = {k: v for k, v in {"storageName": storage_name}.items() if v is not None}
    url = f"/email/storage/folder/{path}"
    if dry_run:
        return {"dry_run": True, "operation": "CreateFolder"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_delete_storage_folder(auth: AsposeAuthClient, path: str, storage_name: str | None = None, recursive: bool | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Deletes a specified folder from Aspose Cloud email storage.  \n\n- **path** – required, string, provided in the URL path; must be a valid folder path such as\u202f`/folder` and cannot be empty.  \n- **storageName** – optional, string, supplied as a query parameter; if omitted the default storage configured for the account is used.  \n- **recursive** – optional, boolean, supplied as a query parameter; set to `true` to delete the folder together with all its subfolders and files, otherwise `false` (or omitted) will delete only an empty folder.  \n\nReturns the raw HTTP response from the Aspose Cloud API, typically a JSON object indicating success or providing error details.'
    params = {k: v for k, v in {"storageName": storage_name, "recursive": recursive}.items() if v is not None}
    url = f"/email/storage/folder/{path}"
    if dry_run:
        return {"dry_run": True, "operation": "DeleteFolder"}
    response = call_with_taxonomy(lambda: requests.delete(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_update_storage_folder_copy(auth: AsposeAuthClient, src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Copies a folder from a source path to a destination path in Aspose Email Cloud storage.  \n- srcPath: required, string, path segment placed in the URL (e.g.\u202f/src); must be a valid existing folder path in the source storage.  \n- destPath: required, string, query parameter (e.g.\u202f/dst); must be a valid folder path where the source folder will be copied.  \n- srcStorageName: optional, string, query parameter; name of the storage that contains the source folder; if omitted the default storage is used.  \n- destStorageName: optional, string, query parameter; name of the storage where the folder will be copied; if omitted the default storage is used.  \nThe tool returns a JSON object containing a boolean field `IsSuccessful` that is true when the folder copy completes, and may include an `ErrorMessage` string describing any failure.'
    params = {k: v for k, v in {"destPath": dest_path, "srcStorageName": src_storage_name, "destStorageName": dest_storage_name}.items() if v is not None}
    url = f"/email/storage/folder/copy/{src_path}"
    if dry_run:
        return {"dry_run": True, "operation": "CopyFolder"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_update_storage_folder_move(auth: AsposeAuthClient, src_path: str, dest_path: str, src_storage_name: str | None = None, dest_storage_name: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    'Moves an existing folder from one location to another within Aspose Cloud storage.  \n\n- **srcPath** – required path‑parameter, string. Must be a valid folder path (e.g., “/folder”) and URL‑encoded if it contains special characters.  \n- **destPath** – required query‑parameter, string. Must be a valid destination folder path (e.g., “/dst”) and URL‑encoded if needed.  \n- **srcStorageName** – optional query‑parameter, string. Name of the source storage; if omitted the default storage is used.  \n- **destStorageName** – optional query‑parameter, string. Name of the destination storage; if omitted the default storage is used.  \n\nThe tool returns the raw HTTP response body from the Aspose Cloud API, typically a JSON object indicating the operation result, including status information and any error messages.'
    params = {k: v for k, v in {"destPath": dest_path, "srcStorageName": src_storage_name, "destStorageName": dest_storage_name}.items() if v is not None}
    url = f"/email/storage/folder/move/{src_path}"
    if dry_run:
        return {"dry_run": True, "operation": "MoveFolder"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if not response.text:
        return {}
    try:
        return response.json()
    except ValueError:
        return {"raw_response": response.text}


def email_get_storage_exist(auth: AsposeAuthClient, storage_name: str) -> StorageExistsResponse:
    'The tool checks whether a specified Aspose Cloud storage container exists.\u202fstorageName (required, string): the exact name of the storage to query, supplied as a path segment in the request URL; it must be a non‑empty identifier.\u202fThe tool returns a JSON object with a single boolean field\u202f`Exists` indicating true if the storage exists and false if it does not.'
    params = {}
    url = f"/email/storage/{storage_name}/exist"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_storage_disc(auth: AsposeAuthClient, storage_name: str | None = None) -> GetDiscUsageResponse:
    'The tool returns the current disc usage statistics for Aspose.Email cloud storage.  \nParameter: storageName – optional query string; if provided, must be the exact name of an existing storage and is omitted to use the default storage.  \nThe output is a JSON object containing numeric fields\u202ftotalSize,\u202fusedSize, and\u202ffreeSize that represent the total, used, and free bytes on the storage.'
    params = {k: v for k, v in {"storageName": storage_name}.items() if v is not None}
    url = "/email/storage/disc"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def email_get_storage_version(auth: AsposeAuthClient, path: str, storage_name: str | None = None) -> GetFileVersionsResponse:
    'Retrieves the complete version history for a specified file stored in Aspose Email Cloud.  \n\n- path (required, string, URL‑path segment): the full file path beginning with “/”, e.g. “/folder/file.ext”.  \n- storageName (optional, string, query parameter): the name of the storage to query; if omitted the default storage is used.  \n\nReturns a JSON object whose “value” field is an array of version objects, each containing properties such as “versionId” (string), “isCurrent” (boolean), “size” (integer, bytes), “lastModified” (ISO‑8601 timestamp), and related metadata.'
    params = {k: v for k, v in {"storageName": storage_name}.items() if v is not None}
    url = f"/email/storage/version/{path}"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})
